### PR TITLE
Rebase on 3.36

### PR DESCRIPTION
**Pull request by mwleeds**
This is a rebase of our master branch on the upstream master branch, which is soon to be released as 3.36. Here are the rebase notes:

pick b38bad31 Allow to reorder pages from the vendor configuration file
drop 16e55a60 copypasta code: Use G_ADD_PRIVATE in CcTimezoneMap (no longer needed, g_type_class_add_private() isn't used upstream any more)
pick 9fef50a6 copypasta code: Use icon name instead of stock icon
pick 2632d2c2 copypasta code: Use GTask in UmRealmManager
pick 34ed71d6 Allow initial setup to switch metrics on and off
pick 5f43781a summary: do not play welcome tour
pick 123fafe3 Add product_serial.conf file
pick 2759e147 account-local: limit full name to 80 characters
pick 90332ce7 account-local: Hide username
pick 17abfc1f account-local: create a shared user account
pick d63e8ace um-utils: consider "shared" username to be in use
pick d97b1a42 main,summary: skip initial setup entirely for shared account
pick 2ac27d13 account-local: username suggestions
drop 9e8be1db password: do not allow empty passwords (this patch is pointless, there's already a strlen(password) > 0 check)
pick 608424a1 password: Show the last character when entering the password
drop e28ddca2 password: add CheckButton to toggle password visibility (reverted by a later commit)
pick 373acf1a password: Add password reminder
pick 6bc732cd Add gis_pkexec() helper function
pick 7d07542f driver: track whether the current session is a live boot
pick 49eb5ad9 pages: Don't show some pages on live sessions
pick bdfb50a1 assistant: add API to show/hide the forward button
pick 4a37e89e eos-test-mode: add eos-test-mode script
pick 9901d406 page-util: Add API to read the EOS image version
pick 57647f97 endless-eula: Add endless eula page
pick e3035813 gnome-initial-setup: don't display privacy page
edit 4f941a51 display: Add a "Display" page to the FBE (update cc-display-config.[ch] and cc-display-config-dbus.c from g-c-c)
pick 82e74da3 keyboard: introduce detector
pick a8ec338b input-chooser: sort default layout before others
pick efe2929d input-chooser: consider only language or country layouts non-extra
pick 28eccc79 input-chooser: Always show the selected layout
pick 1e2f2ad4 keyboard: add us/us+intl default layouts as fallback
pick 53825f8f live-chooser: add the Live Chooser page
pick da2579db summary: show a different message on live sessions
pick cb65b31c Allow pages to specify a GtkAccelGroup
pick baafd64b factory test mode: implement the factory dialog
pick 7a3bd18d language-chooser: make it more clear for the users
pick b948be03 timezone: set default 12h/24h from locale
pick 4288b7c0 Bring back the welcome message/logo
pick 34649497 goa: reorder accounts
pick afae8a16 account-local: add switch for passwordless accounts
fixup 07e3a348 account: Change password switch to a checkbox and rearrange (squashing as noted in the commit message)
pick 09bea58e account,password: Hide password page for passwordless account
pick 1e161fc6 keyboard: manually pass locale to gkbd-keyboard-display
pick adcf5ff2 input-chooser: allow CcInputChooser to expand
pick 959b9946 driver: Inhibit the idle state
pick c235a14b language: allow to specify initial languages from vendor.conf
pick 633cac61 driver: Add "Store Demo"
fixup a05f7ebe fixup! driver: Add "Store Demo"
pick b35fc25f copy-worker: Copy, as opposed to moving files
pick 73d0545a language: make sure initial language is always at the top
pick 14427523 driver: detect whether live media is DVD
pick d788e28e live-chooser: swap USB/DVD assets as needed
pick 81b4f465 endless-eula: Create, but don't show, EULA in store demo mode
pick 02d354f5 language: Change the title to "Welcome to Store Demo" in store demo mode
pick 7b413d9d language: add a button to enter store demo mode on first page
pick ce47c6fb Don't run gnome-initial-setup for existing users
pick 7c4eaaba demo: Reset tracking-id and report a metric when we enable metrics
pick bff74217 passwordPage: make latin kbd layout (en) available for password entries
pick ae11f086 Add powerMenu to initial-setup shell mode
pick e0042142 Launch eos-installer on eosinstaller images
pick 0ce9d626 language: check {unattended,install}.ini on eosinstaller images
pick c1e461b7 page-util: adopt logic to launch eos-installer
pick c39344f4 password: Reset the password page whenever the password page gets hidden
fixup d5026030 password: Reset visibility when page is hidden
pick 43dcb041 network: Update the description for WiFi
pick 2994dd69 site: add page to track site-specific details for deployments
pick 56f9cc30 account: Check configuration to hide password switch if needed
pick 9496d247 timezone: Hide when automatically detected
drop 3dc788f1 network: wait 3 seconds for connectivity check (reverted by a later commit)
pick 05ccab56 account: Allow overriding faces directory from vendor config file
pick a715c915 driver: Make height 768 the threshold for "small screens"
pick 05b6b098 Change generated avatar for empty name
pick 04e525e6 account: Add 'suggested-action' style to photo button
drop 6e256bd0 Revert "password: add CheckButton to toggle password visibility" (dropped the commit being reverted)
pick f6ad5124 driver: Add resource base path
pick 5c0b293d password: Add eye icons to toggle password visibility
pick 3ed1c393 Add darker border to generated avatar
drop 5574639b Add startup log message (this is upstream)
pick 01a3469b Configuration for Transifex
drop 58fd06d7 Add translation support for several new languages (translations will be re-applied at the end)
drop 99499c0d Commit .pot file
drop ce7179a9 Latest translations from Transifex
drop fbd06c4a Merged with downstream translations in Transifex
drop e37691b7 Re-apply intentional downstream translations
drop ca0cce17 Pull from Transifex
pick c31db701 Allow gnome-initial-setup user to run eos-write-location
drop 1b2922e0 Updates from Transifex
drop d92aac9b assistant: mark "Accept" button as suggested action (this is upstream)
pick 88e1d75d account: Use control-center setting to override faces
fixup 59472473 avatars: Don't crash if control center schema isn't present
fixup 9942ba15 avatars: Get facesdirs setting from gsettings-desktop-schemas
drop 7cfc33e2 Updates from Transifex
drop 3ff67448 Updates from Transifex
drop 0dd0044e Revert "Updates from Transifex"
drop f3ba64a7 Updates from Transifex
pick 958d2f32 driver: detect when in live mode with persistence
pick bfdece15 summary: show a different message on persistent live sessions
pick 0fdb5cdc Show all pages in persistent live mode
pick ffb3e005 live-chooser: don't create live user account when in persistent live mode
drop 08861d76 Updates from Transifex
drop 085155e4 Revert "Updates from Transifex"
drop 5021d93c Updates from Transifex
drop 3b6e2cde NEWS for 3.34.1 (from the gnome-3-34 branch)
drop ee3e46fb Update .pot file
drop d21113bb Updates from Transifex
drop 4dd16b8b Updates from Transifex
drop 3a3565d7 Updates from Transifex
drop 540c0077 New translations from Transifex
drop 77a51d57 New translations from Transifex
drop 47981dcb Revert "network: wait 3 seconds for connectivity check" (dropped the commit being reverted)
drop a2c5ec0a New translations from Transifex

https://phabricator.endlessm.com/T28787

### CODE REVIEW

**Comment by mwleeds** [comment]
TODO:

- [ ] Compile test this
- [ ] Smoke test this
- [ ] Re-apply downstream translations
- [ ] Enumerate situations that should be Dev QA'd (parental controls, live mode, persistent live mode, etc.)
- [ ] Ideally, upstream some of this, but that shouldn't block merging
- [ ] File a ticket about rebasing again on released 3.36 version, which should be only a minor delta away from this
- [ ] Update the packaging branch

**Comment by andrunko** [comment]
> TODO:
> * [ ]  File a ticket about rebasing again on released 3.36 version, which should be only a minor delta away from this

I was thinking of reusing the same ticket to update to 3.35.9x and then 3.36 when it is out, to avoid having 2 tickets to update each GNOME component we maintain on git.

**Comment by mwleeds** [comment]
> This could probably be rebased on the upstream `3.35.92` tag which has been pushed since you started rebasing (since it’s probably the version which Debian are going to do their packaging work on, and it contains commit 5a655312 which we could do with).

Done
> 
> `fixup! password: Add password reminder` hasn’t been squashed down yet.

Done
> What’s happening with this comment from commit “account-local: limit full name to 80 characters”?
> 
> > TODO: This patch is wrong. The limit is 80 bytes, not 80 characters, as
> > confirmed by Will's testing in https://phabricator.endlessm.com/T25360.
> > There is a ticket open, and if it is addressed before a following
> > rebase, then it should be squashed into this commit:
> > https://phabricator.endlessm.com/T25444
> 
I saw that, but the linked ticket is still open. The full fix of changing accountsservice seems out of scope for now, but we could throw a length check into `is_valid_name()`. I added a commit to this branch with that.

> Commit `f68f3201 account: Use control-center setting to override faces` could probably be squashed into “b926a45c account: Allow overriding faces directory from vendor config file”

Good point, done.

**Comment by mwleeds** [comment]
I created [this upstream MR](https://gitlab.gnome.org/GNOME/evince/-/merge_requests/227) to silence some of the deprecation warnings emitted when this branch is compiled.

**Comment by mwleeds** [comment]
I pushed the packaging to `debian-T28787`, but since it's now based on Debian's git rather than tarballs the commit history is different and I can't submit it as a PR against `debian-master`.

I also pushed `Version_3.36.0` and `Version_3.36.0_debian` tags.

**Comment by mwleeds** [comment]
bot, retest this please

**Comment by mwleeds** [comment]
bot, retest this please

(I put the `Version_3.36.0` tag on the wrong commit, it's fixed now.)

**Pull request merged**
