### PR TITLE
Add clubhouse component to initial-setup session mode

### PR DESCRIPTION
**Pull request by cosimoc**
We depend on that component to display quest dialogs.

https://phabricator.endlessm.com/T24279

### CODE REVIEW

**Comment by erikos** [comment]
Looks good, thanks Cosimo, merged.

**Comment by joaquimrocha** [comment]
@cosimoc (I haven't tested this but...) Do we need to change the button manager so it doesn't display the open button in the session mode?

**Comment by cosimoc** [comment]
@joaquimrocha Yes, that should be another follow up.

**Comment by cosimoc** [comment]
Filed https://phabricator.endlessm.com/T24404

**Pull request merged**
